server:
  port: 8080

external:
  conference:
    host: http://myunghoon-conference-alb-1395603225.ap-northeast-2.elb.amazonaws.com
  login-member:
    host: http://myunghoon-member-alb-973600884.ap-northeast-2.elb.amazonaws.com
  analysis:
    host: http://myunghoon-analysis-alb-174906274.ap-northeast-2.elb.amazonaws.com
  event:
    host: http://myunghoon-conference-alb-1395603225.ap-northeast-2.elb.amazonaws.com

auth:
  secret-key: secret-key

